name: Deploy Preview
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    steps:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build main project and demo for GitHub Pages
        run: npm run build
        env:
          GITHUB_PAGES: 'true'
        
      - name: Verify demo build
        run: |
          echo "Checking demo build output..."
          ls -la ./demo/dist/
          echo "Demo files:"
          find ./demo/dist/ -type f -name "*.html" -o -name "*.js" -o -name "*.css"
  
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          preview-branch: main
          source-dir: .
          umbrella-dir: pr-preview
          action: auto