name: Publish to GitHub Packages

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  publish_to_github_packages:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.16.0'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@sharinpix'
          
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable
          
      - name: Install ChromeDriver
        uses: browser-actions/setup-chromedriver@v1
        with:
          chrome-version: stable
          
      - name: Verify Node.js version
        run: node -v
        
      - name: Install dependencies
        run: npm ci
        
      - name: Start application
        run: npm start
        env:
          CI: true
          
      - name: Wait for application to start
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:5003; do
            printf '.'
            sleep 0.1
          done
          
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_TOKEN }}
